#端口号
server:
  port: 9090
#mybatis
mybatis:
  type-aliases-package: com.zbw.fame.Model
#mapper
mapper:
  mappers: com.zbw.fame.util.MyMapper
  not-empty: false
  identity: MYSQL
spring:
  #mail
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #默认properties
  profiles:
    active: dev



