#端口号
server:
  port: 9090
spring:
  #mail
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #默认properties
  profiles:
    active: dev



